# Generated by Django 5.0.7 on 2024-07-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='payment_complete',
            field=models.BooleanField(default=False),
        ),
    ]
